### ISSUE TITLE
Audio loss on MotoTRBO XPR series

### ISSUE THREAD

**Issue by va2na** [g4klx/MMDVM#101]
Hi Jonathan,

We have a couple of user that have audio loss problem on motorola XPR 6550-4500 series. 

Audio loss is just after receiving ID from the repeater. and held 2 secondes,  Talker Alias is disabled on each repeater and we still got the issue.

Can send video for more detail.

Thank you

**Comment by dl7ata** [comment]
I got the same effect with the similar DP3600 on my hotspot.
Audio is loss for about 1 sec. and I can't receive any SMS (caused by this delay?).
Regards
Frank

**Comment by citynetcomputing** [comment]
Same issue here... XPR7550e.

**Comment by dl7ata** [comment]
Whats your jitter-value in your MMDVM.conf ?

**Comment by citynetcomputing** [comment]
standard 300

**Comment by citynetcomputing** [comment]
its RF to RF anyway. Has nothing to do with Jitter. ;)

**Comment by dl7ata** [comment]
What do you mean by "RF to RF"? 
Set it to zero, this should work for the audio delay but not for missing SMS.

**Comment by citynetcomputing** [comment]
Radio to Radio through the Repeater. No internet, No linking. etc..

**Comment by dl7ata** [comment]
I don't know your setup. How is the digital stream running? From one radio strait into another? In that case forget jitter.

**Comment by citynetcomputing** [comment]
No Its an MMDVM PI based DMR repeater.

**Comment by dl7ata** [comment]
Did you try jitter=0 ?

**Comment by citynetcomputing** [comment]
Jitter is only for the DMR gateway link so no. Has nothing to do with my issue but thanks!
