### ISSUE TITLE
make clean nucleo error

### ISSUE THREAD

**Issue by faxe2110** [g4klx/MMDVM#116]
After last git pull im having this problem,

Makefile:216: recipe for target 'obj_f4/SerialRB.o' failed
make: *** [obj_f4/SerialRB.o] Error 1
pi@raspberrypi:~/Applications/MMDVM $

73 SA7BNT
Tim

**Comment by phl0** [comment]
You have to update the STM32F4XX_Lib inside the MMDVM folder. The lib has been updated by @juribeparada 6 days ago and includes the definitions for NULL which is causing the error here.

**Comment by faxe2110** [comment]
Thanks, that was the problem.
