### ISSUE TITLE
RSSIRB.cpp:25:8: error: 'NULL' was not declared in this scope

### ISSUE THREAD

**Issue by workino** [g4klx/MMDVM#118]
Hello,
i'm trying to compile MMDV for nucleo but i got this error:

RSSIRB.cpp: In constructor 'CRSSIRB::CRSSIRB(uint16_t)':
RSSIRB.cpp:25:8: error: 'NULL' was not declared in this scope
 m_rssi(NULL),

how can i solve it?

Regards
Gabriele

**Comment by phl0** [comment]
See https://github.com/g4klx/MMDVM/issues/116
