### ISSUE TITLE
Received a NAK from the MMDVM, MMDVM_DSTAR_DATA, data overflow, space = (number)

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVM#13]
...where the numbers are : 4  or  9  or 3

New issue in the log of MMDVM

see the picture attached

thank you
73
![capture](https://cloud.githubusercontent.com/assets/16877668/16989809/ecf5211c-4e95-11e6-9d47-532d0e1ef862.JPG)

**Comment by g4klx** [comment]
It looks like you're running old versions of the host and firmware. Please update both and try again.

**Comment by iw9grl** [comment]
Hi Jonathan, 

normally I update both MMDVM and MMDVMHost .
I also updated today .... I will leave the system under test .....

tnx
73

**Comment by iw9grl** [comment]
The last update on both MMDVM and HOST write in the log the same messages ......

**Comment by iw9grl** [comment]
Closed , for now the issue seems to be solved .
tnx
