### ISSUE TITLE
Audio loss on MotoTRBO XPR series 

### ISSUE THREAD

**Issue by va2na** [g4klx/MMDVM#144]
Hello Jonathan,

Motorola user experience audio loss and DMR id loss of few sec at begin of Voice call intermittantly.  
maybe 10% ratio.

This happen from RF to RF communcation and i found that using TYT debug mode and DSD+ what happen each time.  The MMDVM send 3 voice header follow by the super voice frame, but when the glitch occur there 1, 2 or 3 idle frame added between the 3 Voice hdr, just look in the picture..and i confirm...each time we loss the audio in the Motorola...there an unwainted idle frame between the 3 Voice Hdr.

I hope it help

Guillaume
![dmrerror](https://user-images.githubusercontent.com/18428819/35744737-0d3e66ac-080f-11e8-904a-83a97b4f3a5e.jpg)

**Comment by va2na** [comment]
Another one

![dmr2](https://user-images.githubusercontent.com/18428819/35744921-9ea171a2-080f-11e8-9e9f-7162e0249df0.jpg)

**Comment by aminhusni** [comment]
Have you checked Issue #127 ? Might be related.

**Comment by citynetcomputing** [comment]
Same issue, MMDVM Repeater, TYT MD380 cannot talk to XPR7550e. XPR keeps dropping.

**Comment by citynetcomputing** [comment]
anyone working on this issue??
