### ISSUE TITLE
pistar-mmdvmcal is not working

### ISSUE THREAD

**Issue by xe2pmp** [g4klx/MMDVM#154]
Hi guys!
I updated the mmdvm firmware 02/23/2018, and the pistar-mmdvmcal is not working.
Version: 1 "MMDVM 20180223 TCXO (D-Star/DMR/System Fusion/P25/NXDN/RSSI/CW Id) (Build: 15:34:57 Feb 23 2018)"
Got a NAK from the modem
Starting Pi-Star Services...
Finnished...

**Comment by juribeparada** [comment]
You need to update your MMDVMCal too. Probably Pi-Star version of MMDVMCal is still old.

**Comment by xe2pmp** [comment]
Hi Andy!
In fact, it stopped working after compiling and installing the new software for mmdvm.
Previosly just run the sudo pistar-mmdvmcal and that´s it.
Well, I have to find out how to do it.
regards
Pablo
xe2pmp
  ----- Original Message -----

**Comment by xe2pmp** [comment]
Done,
After of updated the MMDVMCal, it is working.
