### ISSUE TITLE
Feature Request: Add TX/RX Offset to MMDVMCal

### ISSUE THREAD

**Issue by mrickey** [g4klx/MMDVM#157]
Adjusting TX and RX Offset for hotspots is tedious, unless I'm missing something.

You have to edit the MMDVM.ini file, restart services and see if it's any better.

I would like to see something in MMDVMCal that would work similar to the audio levels.

For RXOffset, I would see keying up a radio (DMR for example) and having the ability to adjust RXOffset up and down while there is a display showing packet loss. This would let me dial it in quickly. I could then update MMDVM.ini manually and be done.

For TXOffset, it would be more difficult. I guess the hotspot would have to generate a signal and let the use adjust up and down to find the upper and lower boundaries (where the radio has issues receiving the signal) and then something the offset to the mid point.

Does this seem doable? Is there any easier way?

Thanks in advance,

Michael AF6FB

**Comment by juribeparada** [comment]
We have now BER reading in MMDVMCal, and you can change the frequency of your MMDVM_HS board (also with MMDVMCal) and then have the Offset.
