### ISSUE TITLE
EXTERNAL CLOCK 19.2Mhz Problem.

### ISSUE THREAD

**Issue by ik6qoo** [g4klx/MMDVM#16]
I'm compiled the last version of MMDVM with C4FM / DMR Filter and when i enable the external clock the led of TX is always ON and the modem not decode .
With internal clock is all ok .
I have not tried others TXCO ( 12 or 14.4 ) but I am sure that my clock 19.2 is mounted properly and running.
What could be the problem ?
it's an error of code ??

73s de IK6QOO Gianluca

**Comment by iw9grl** [comment]
Gianluca, prova a premere il pulsante di reset dopo aver alimentato arduino dall'usb.... Se funziona ho la soluzione.... 73

**Comment by ik6qoo** [comment]
Grazie del suggerimento  , domani  ricarico il firmware per il TXCO esterno e provo nuovamente .

 

Da: iw9grl [mailto:notifications@github.com] 
Inviato: venerdì 5 agosto 2016 19.55
A: g4klx/MMDVM <MMDVM@noreply.github.com>
Cc: ik6qoo <ik6qoo@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [g4klx/MMDVM] EXTERNAL CLOCK 19.2Mhz Problem. (#16)

 

Gianluca, prova a premere il pulsante di reset dopo aver alimentato arduino dall'usb.... Se funziona ho la soluzione.... 73

**Comment by ik6qoo** [comment]
Provato il reset ma non funziona .. Ho misurato con un frequenzimetro il pin di arduino dove è collegato il TXCO e leggo perfettamente 19,2Mhz .

**Comment by iw9grl** [comment]
Stai alimentando il quarzo dai 3.3v di arduino o stai regolando i 5v???  Io avevo un drop sui 3.3v col quarzo collegato e non funzionava nulla, alimentando il quarzo dai 5v con un 78l33 tutto ha funzionato. 73

**Comment by ik6qoo** [comment]
Ho un regolatore da 3.3 collegato ai 5V di arduino ( schema SP8NHT) , dici di prendere i 3,3 direttamente da arduino ?

**Comment by iw9grl** [comment]
No non è necessario.... A questo punto non so cosa possa essere, mi spiace

**Comment by ik6qoo** [comment]
Secondo me è un errore dell’attuale firmaware  , aspetto nuovi sviluppi . Grazie  comunque !

 

Da: iw9grl [mailto:notifications@github.com] 
Inviato: martedì 9 agosto 2016 19.09
A: g4klx/MMDVM <MMDVM@noreply.github.com>
Cc: ik6qoo <ik6qoo@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [g4klx/MMDVM] EXTERNAL CLOCK 19.2Mhz Problem. (#16)

 

No non è necessario.... A questo punto non so cosa possa essere, mi spiace

**Comment by ik6qoo** [comment]
Risolto con external clock 12mhz tutto OK .

**Comment by vk4tux** [comment]
The clip sine wave txco is not a good design, Use HCMOS > 12.0000 MHz ;

bridge connections >  R2, R26, C22    |   IC4 not installed, R20 not 
installed & not bridged. (C20 & others pending install)

http://vk4tux.duckdns.org/6.1/20160818_154426.jpg

**Comment by ik6qoo** [comment]
solved with external clock 12MHz .

TNX

**Comment by vk4tux** [comment]
19.2 or 14.4 or 12.288 work just as well.
