### ISSUE TITLE
NAK Problem

### ISSUE THREAD

**Issue by SA7BNT** [g4klx/MMDVM#163]
Hallo i´m using ZUM 1.0 and Arduino Due 
Just updating (git pull) and upload but running in at some issue 

M: 2018-03-24 13:20:51.407 Opening the MMDVM
I: 2018-03-24 13:20:53.418 MMDVM protocol version: 1, description: MMDVM 20180223 TCXO (D-Star/DMR/System Fusion/P25/NXDN/RSSI/CW Id) (Build: 13:18:56 Mar 24 2018)
E: 2018-03-24 13:20:53.438 Received a NAK to the SET_CONFIG command from the modem

**Comment by juribeparada** [comment]
You probably need to update your MMDVMHost too. I don't have any problem with latest fw and MMDVMHost
