### ISSUE TITLE
Experiencing "hang" om update at "Updating Hostfiles"...

### ISSUE THREAD

**Issue by TheOriginalFreddoFrog** [g4klx/MMDVM#175]
Hi Folks,

Observed on 2 systems … one accessed via a terminal server and the other accessed directly on the same network...

Starting update, please wait...
Stopping Services...
Done
Updating DV Binaries...
From https://github.com/AndyTaylorTweet/Pi-Star_Binaries
* branch master -> FETCH_HEAD
Already up-to-date.
Done
Updating Pi-Star Binaries...
From https://github.com/AndyTaylorTweet/Pi-Star_Binaries_sbin
* branch master -> FETCH_HEAD
Already up-to-date.
Done
Updating Hostfiles…_**

…….

It just sits here doing nothing at this point !!

Is this a temporary issue?

How can I download the hostfiles (in fact the entire update set) manually from the command line?

Is the pi-star image open read-write during/after this hang?

Thanks

Steve I

**Comment by juribeparada** [comment]
This is for MMDVM firmware. For Pi-Star specific issues, please ask here: https://forum.pistar.uk
