### ISSUE TITLE
No A0 decoding on SP8NTH option

### ISSUE THREAD

**Issue by vk4tux** [g4klx/MMDVM#18]
closed

**Comment by g4klx** [comment]
The IO for the NTH board hasn't changed for a long time and no-one else has complained about it not working. Can I suggest you ask on the group about it? It may be an idea to switch the RSSI option off as it's known not to work on the non rssi branch anyway.

**Comment by vk4tux** [comment]
It is now working , incl with rssi and PWM options. On latest FW and 
host. I had to modify the SP8NTH V6.1 hardware design to work on 
12.5KHz, i.e Taits TM8110's which I use.

It is all good thankyou. There was no issue with the FW of course.
