### ISSUE TITLE
Make nucleo error

### ISSUE THREAD

**Issue by zl3dmh** [g4klx/MMDVM#182]
After latest firmware download I am unable to compile and get the error below,

![make nucleo error](https://user-images.githubusercontent.com/41130498/42602640-789b2af2-85be-11e8-94d6-49c7b6dd7bb6.PNG)

73s zl3dmh
Doug

**Comment by juribeparada** [comment]
Please check now, I added a temporary pin definitions for POCSAG and F446/F722. I can't test by myself until Sunday when return to home.

**Comment by phl0** [comment]
At least it compiles cleanly now :)

**Comment by zl3dmh** [comment]
Compiled OK now Thank you..
