### ISSUE TITLE
Teensy implementation b0rken

### ISSUE THREAD

**Issue by phl0** [g4klx/MMDVM#188]
As noted in https://github.com/g4klx/MMDVM/commit/46528127dcd9f13120d281cd0109cc1db6d1dbf9#commitcomment-30165730 the Teensy implementation seems to be broken currently. The SVC LED stops blinking after connection from MMDVMCal/MMDVMHost and the modem is in a state where it does not respond to read of firmware versions. The commit that introduced the issues is 46528127dcd9f13120d281cd0109cc1db6d1dbf9 whereas b34d3c3dbd6e0d2ecae8aca5102fb2d749e4e39c does not show the issues.
I manually applied the changes in IO.h and IO.cpp to 46528127dcd9f13120d281cd0109cc1db6d1dbf9 and it still works. No more ideas currently.

**Comment by juribeparada** [comment]
I reduced the buffers for Teensy 3.2/3.1, can you test that?. I tested with Teensy 3.2 and seems to work OK for me at least.

**Comment by phl0** [comment]
Hmm I tested with my Teensy 3.2 board on F0DEI PCB but the problem is still existing. Starting MMDVMCal causes the SVC to go off.

**Comment by mjswiatk** [comment]
FWIW, Here are my latest findings:
Teensy 3.2
Last working is version 
b34d3c3
on Feb 7, 2018

Teensy 3.6
Last working version
3875da8
on Nov 2, 2018

**Comment by mjswiatk** [comment]
Correction
Teensy 3.2
Last working is version 
b34d3c3
on Feb 7, 2018



Teensy 3.6
Last working version
b4647d8
on Oct 23, 2019

**Comment by mjswiatk** [comment]
Update:
 Teensy 3.2
Last working is version 
78ae7f3
on Feb 9, 2018


Teensy 3.6
Last working version
4d664c4
on Apr 25, 2020

Still, I cannot get anything much newer working on 3.2 which is unfortunate since there are DMR issues with the old code from 2018.

**Comment by phl0** [comment]
As the board is outdated and there are better platforms I am going to close this issue.
