### ISSUE TITLE
MMDVM HS_HAT_Duplex - Raspberry PI3+ duplex issue

### ISSUE THREAD

**Issue by mwelby** [g4klx/MMDVM#197]
Hi - I have an issue that when I transmit on my MD380 in Duplex mode (Tx and Rx Offsets set) - I cannot connect to the hat - On the MD380 I get the red led indicator flashing instead of a permanent red indicating TX connected.

If I look at the logs I am getting the error: Invalid Downlink Activate received from xxxxx

I am using firmware v1.4.8

**Comment by juribeparada** [comment]
The place for personal hotspot firmware (MMDVM_HS) issues is here: https://github.com/juribeparada/MMDVM_HS
If you read the "Known issues" in README, you will see your problem could be solved increasing DMR deviation a little.
