### ISSUE TITLE
Specify Units In Expert Settings(and other applicable)

### ISSUE THREAD

**Issue by aminhusni** [g4klx/MMDVM#199]
Just a suggestion, maybe should have some units on what do the numbers represent.
Like the Rx offset and Tx offset, what do the numbers mean? Are they in Hz? KHz? etc. 

![screenshot_378](https://user-images.githubusercontent.com/8511047/47609314-b30c8500-da6e-11e8-9fa6-d808223739d4.png)

**Comment by g4klx** [comment]
This is a Pi-Star issue and not related to the MMDVM as such. Contact the Pi-Star people about it.
