### ISSUE TITLE
MMDVM_POG STM32F105 stop working TX after 175 second

### ISSUE THREAD

**Issue by sp2ong** [g4klx/MMDVM#215]
Hi,

We have use board MMDVM_POG STM32F105 with MMDVM firmware 20190130 version and lastest MMDVMHost on our repeater. After every 175 second transmission in DMR mode, the MMDVM_POG board is frozen. PTT is ON, COS led is light. Only Power off/on help to works  MMDVM_POG again. 

In MMDVM.ini the TIMEOUT is value 240 seconds.

If we set the timeout value lower than 175 s for example 160 the timeout works and MMDVM_POG board not frozen and we can start new transmission.

The problem is when we use MMDVM_POG on the repeater (DUPLEX ) mode and local user RF start use
But when traffic is incoming from the network the TX works without problem 175 seconds. It looks like a problem in duplex mode when is traffic incoming from RF and TX frozen after 175 seconds

Video 
https://www.youtube.com/watch?v=-UD0iMUqc2w&t=

Does anybody meet a similar problem?

**Comment by sp2gch** [comment]
Yes, I have exactly the same problem and just turning off the power and turning on helps until the same time.

**Comment by sp2ong** [comment]
I suppose that it is problem TCXO
