### ISSUE TITLE
MMDVM FM BRUNCH ISSUE

### ISSUE THREAD

**Issue by SA7BNT** [g4klx/MMDVM#244]
Hey, 

im getting this issue. Can someone explain for me why.

73
Tim (SA7BNT)

<img width="1216" alt="Bildschirmfoto 2020-05-02 um 15 42 35" src="https://user-images.githubusercontent.com/35367117/80865790-d92a6b00-8c8b-11ea-954d-a6f609debec7.png">

**Comment by sp2ong** [comment]
You need to uncomment this line:

// #define USE_ALTERNATE_FM_LEDS

 In Config.h 

More information see on: https://groups.io/g/OpenDV/topic/73281878#236

**Comment by SA7BNT** [comment]
Thanks for answer sp2ong,
what a stupid issue now it´s working!!!

Objcopy from ELF to BINARY complete!
73 SA7BNT
