### ISSUE TITLE
Received a NAK to the SET_CONFIG command from the modem

### ISSUE THREAD

**Issue by NQ4Y** [g4klx/MMDVM#247]
Hi,
Running Zum 1.0.1 via USB on RPi.

Update commands used:
  git clone https://github.com/g4klx/MMDVM.git
  cd MMDVM
  vi Config.h        
  pistar-watchdog.service stop
  systemctl stop mmdvmhost.timer
  systemctl stop mmdvmhost.service
  make -f Makefile.Arduino compile
  make -f Makefile.Arduino upload

Update successfully loads to flash.

From Pi-Star 3.4.17 the log file indicates:

M: 2020-05-07 21:16:29.278 Opening the MMDVM
I: 2020-05-07 21:16:31.290 MMDVM protocol version: 1, description: MMDVM 20200506 (D-Star/DMR/System Fusion/P25/NXDN/POCSAG/FM) 12.0000 MHz GitID #eb9c0df
E: 2020-05-07 21:16:31.310 **Received a NAK to the SET_CONFIG command from the modem**

What do I need to do to correct this issue? The firmware from 29 Apr 2020 works fine but the firmware from 7 May 2020 returns the NAK from the SET_CONFIG command. The Pi-STAR modem is type is set to MMDVM/MMDVM-HS/Teensy/ZUM (USB).

thank you!

Terry NQ4Y

**Comment by m0vse** [comment]
That is because the protocol has changed in the latest firmware (addition of FM mode), you will need to recompile MMDVMHost as well to use the new firmware, or speak to the Pi-star developers.

**Comment by NQ4Y** [comment]
Thank you!
