### ISSUE TITLE
MMDVM_POG V. 20200520 does not work

### ISSUE THREAD

**Issue by rn6ljt** [g4klx/MMDVM#282]
The MMDVM_POG Board does not work with the new program v.20200520
works with Tolka v.20200506 
fix it please
thank you very much for Your work

**Comment by badtime** [comment]
I have already reported the issue here https://github.com/g4klx/MMDVM/issues/277 but no answer.

**Comment by g4klx** [comment]
The POG board does not have enough computing power to do the more modern things that the MMDVM can do. You need to upgrade your hardware or stay with the older version. This was completely discussed on the OpenDV@groups.io list.
