### ISSUE TITLE
CAX25TX ax25TX;

### ISSUE THREAD

**Issue by iddq** [g4klx/MMDVM#299]
https://github.com/g4klx/MMDVM/blob/8d9b49bdb04c72e9080dc8702d9508eea50d9903/MMDVM.ino#L63

**Comment by iddq** [comment]
CAX25 does not exist. should it be CAX25TX?

**Comment by g4klx** [comment]
You are quite right, it should be CAX25TX. I've fixed it. However I am not sure than an Arduino Due will be powerful enough to run this version of the firmware.

**Comment by iddq** [comment]
for the decoding?
