### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by pe1bzf** [g4klx/MMDVM#5]
Hi, 

when loading the MMDVM-master into the Arduino compiler,
i get this error: (previous version compiled well).
It look like the library cannot be found

please advice.

73
William, PE1BZF

Arduino: 1.6.8 (Windows 10), Board:"Arduino Due (Programming Port)"

Arduino: 1.6.8 (Windows 10), Board:"Arduino Due (Programming Port)"

Arduino: 1.6.8 (Windows 10), Board:"Arduino Due (Programming Port)"

C:\MMDVM\MMDVM.ino:19:20: fatal error: Config.h: No such file or directory

 #include "Config.h"

                    ^

compilation terminated.

exit status 1
Error compiling for board Arduino Due (Programming Port).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by phl0** [comment]
I just compiled the latest MMDVM firmware on a Windows 7 Pro machine running Arduino 1.6.9. It was only moaning about some redefinitions of variables but in the end it compiled successfully.
