### ISSUE TITLE
Warning during verify - CCalRRSI

### ISSUE THREAD

**Issue by iw9grl** [g4klx/MMDVM#54]
![image](https://cloud.githubusercontent.com/assets/16877668/21548239/87ccf316-cdeb-11e6-9cdf-6f2c3a22451d.png)

73

**Comment by g4klx** [comment]
Thanks.

I'll get onto it.

Jonathan G4KLX

**Comment by iw9grl** [comment]
![image](https://cloud.githubusercontent.com/assets/16877668/21565099/060241de-ce94-11e6-9806-3baa2b98ecdf.png)

**Comment by g4klx** [comment]
Fixed :-)

**Comment by iw9grl** [comment]
GOOD !!!!
