### ISSUE TITLE
MMDVM RF CW CALLSIGN

### ISSUE THREAD

**Issue by Emamisu** [g4klx/MMDVM#79]
Hello,
the Italian callsing authorization bureau (Ministero dello Sviluppo Economico) is very slow to assign the callsign for repeater. We can send the request to bureau and after 90 days put on the repeater with a temporary callsing. The temporary call is on this formula: I-IRX-XXXXXX (es: I-IR2-IU2CIQ).
MMDVM not allow more than 8 characters name.
You can MMDVM able to send a 12 character or more CW RF ID?

Ciao
Emanuele IU2CIQ

**Comment by phl0** [comment]
This is not an issue of the MMDVM firmware but of MMDVMHost. There is already issue covering this: https://github.com/g4klx/MMDVMHost/issues/294
Pls close this issue.
