### ISSUE TITLE
D-STAR Not Always Recognized

### ISSUE THREAD

**Issue by mrickey** [g4klx/MMDVM#92]
I'm comparing notes with another user of the ZUMspot. We are both having issues with D-STAR mode getting recognized.  In both cases we have multiple modes enabled on the ZUMspot and can see the lights scanning.

When I key up, I will see the lights continue scanning for about 3 cycles before the ZUMspot locks into D-STAR mode.

The other person is keying up several times before he can get it to lock in. I asked him to stay on the PTT until it locks is, just as I did. But I haven't heard back from him.

Is this a known issue? Is there a configuration change that would help?

Thanks in advance,
Michael AF6FB

**Comment by phl0** [comment]
That should be handled as an issue for the HotSpot FW on https://github.com/juribeparada/MMDVM_HS/issues
